//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGame_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenges
    {
        public int challenge_id { get; set; }
        public Nullable<int> challenger_id { get; set; }
        public Nullable<int> challenged_id { get; set; }
        public Nullable<System.DateTime> challenge_date { get; set; }
        public string status { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
