//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonGame_Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokemon()
        {
            this.Medical_Attention = new HashSet<Medical_Attention>();
            this.Pokedex = new HashSet<Pokedex>();
            this.Pokemon1 = new HashSet<Pokemon>();
            this.Team_Pokemon = new HashSet<Team_Pokemon>();
        }
    
        public int pokemon_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string weakness { get; set; }
        public Nullable<decimal> weight { get; set; }
        public int number { get; set; }
        public Nullable<int> evolves_from { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medical_Attention> Medical_Attention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pokedex> Pokedex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pokemon> Pokemon1 { get; set; }
        public virtual Pokemon Pokemon2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team_Pokemon> Team_Pokemon { get; set; }
    }
}
